# Whether or not to enable the server. If this is false, the server won't run (this is required to prevent the server from restarting after being installed in the active deployment's case)
enable: false
# The port to run the server on
port: 5000
# The IP/hostname to run the server on
hostname: localhost
# CORS settings
cors: false
# Debug logging settings
logging: false
# Discord settings
discord:
  id: 'an id'
  secret: 'a secret'
  url: 'https://your.url/'
# SSL settings
ssl:
  # Use ssl
  enable: false
  # Key and fullchain location from the location of index.js
  location:
    folder: './data/ssl/'
    key: './data/ssl/ssl.key'
    fullchain: './data/ssl/full.chain'
# Raxcoin settings
daily: 1000