# Whether or not to enable the config. If this is false, the server won't run (this is required to prevent the server from restarting after being installed in the active deployment's case)
enable: false
# The port to run the server on
port: 5000
# The IP/hostname to run the server on
hostname: localhost
# SSL settings
ssl:
  # Use ssl
  enable: false
  # Key and fullchain name (these will be stored inside ../src/ssl/, so write them assuming you're inside ../src/ssl/)
  location:
    key: './your.key'
    fullchain: './full.chain'
  # In the active deployment's case, SSL certificates need to be copied from the original certificates to local ones. When no certs are found in ../src/ssl/, a script is run and replaces them. If for whatever reason you need to do something like this too, enable this to delete certificates when the application is stopped using the stop command.
  forceRegen: true