# Whether or not to enable the config. If this is false, the server won't run (this is required to prevent the server from restarting after being installed in the active deployment's case)
enable: false
# The port to run the server on
port: 5000
# The IP/hostname to run the server on
hostname: localhost
# SSL settings
ssl:
  # Use ssl
  enable: false
  # Key and fullchain name (these will be stored inside ../data/ssl/, so write them assuming you're inside ../data/ssl/)
  location:
    key: './your.key'
    fullchain: './full.chain'
